# 基础设置
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
#set -g allow-passthrough on

set -g mouse on                          # 启用鼠标支持
setw -g mode-keys vi
setw -g automatic-rename off
set -g history-limit 10000               # 增大滚动历史
set-option -sg escape-time 10


# 前缀键优化（避免与常用快捷键冲突）
unbind C-b
set -g prefix C-k
bind C-k send-prefix

# 窗口状态（关键修正）
setw -g window-status-format "#[fg=colour248,bg=colour235] #I:#W "
setw -g window-status-current-format "#[fg=colour255,bg=colour240,bold] #I:#W "

# 窗口/面板操作
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind r source-file ~/.tmux.conf \; display "Reloaded!"  # 重载配置

set-window-option -g pane-base-index 1
bind-key k select-pane -U
bind-key j select-pane -D
bind-key h select-pane -L
bind-key l select-pane -R

bind -r K resizep -U 5
bind -r J resizep -D 5
bind -r H resizep -L 5
bind -r L resizep -R 5


# 状态栏美化
set -g status-bg colour235
set -g status-fg colour137
set -g status-left "#[fg=green]#S #[fg=colour245]» "
set -g status-right "#[fg=colour245]« #[fg=colour137]%Y-%m-%d %H:%M"
